create table matches as
select season, stage, home_team_goal, away_team_goal, 
home_player_x1,
home_player_x2,
home_player_x3,
home_player_x4,
home_player_x5,
home_player_x6,
home_player_x7,
home_player_x8,
home_player_x9,
home_player_x10,
home_player_x11,
away_player_x1,
away_player_x2,
away_player_x3,
away_player_x4,
away_player_x5,
away_player_x6,
away_player_x7,
away_player_x8,
away_player_x9,
away_player_x10,
away_player_x11,
home_player_y1,
home_player_y2,
home_player_y3,
home_player_y4,
home_player_y5,
home_player_y6,
home_player_y7,
home_player_y8,
home_player_y9,
home_player_y10,
home_player_y11,
away_player_y1,
away_player_y2,
away_player_y3,
away_player_y4,
away_player_y5,
away_player_y6,
away_player_y7,
away_player_y8,
away_player_y9,
away_player_y10,
away_player_y11,
home_player_1,
home_player_2,
home_player_3,
home_player_4,
home_player_5,
home_player_6,
home_player_7,
home_player_8,
home_player_9,
home_player_10,
home_player_11,
away_player_1,
away_player_2,
away_player_3,
away_player_4,
away_player_5,
away_player_6,
away_player_7,
away_player_8,
away_player_9,
away_player_10,
away_player_11
from match_all

create table players_data as
select player_name, birthday, height, weight, overall_rating, potential, preferred_foot, attacking_work_rate, defensive_work_rate, crossing,
finishing, heading_accuracy, short_passing, volleys, dribbling, curve, free_kick_accuracy, long_passing, ball_control, acceleration, sprint_speed,
agility, reactions, balance, shot_power, jumping, stamina, strength, long_shots, aggression, interceptions, positioning, vision, penalties, marking, standing_tackle, 
sliding_tackle, gk_diving, gk_handling, gk_kicking, gk_positioning, gk_reflexes
from players_all

create table teams_data as
select team_long_name, buildUpPlaySpeed, buildUpPlaySpeedClass, buildUpPlayDribbling, buildUpPlayDribblingClass, buildUpPlayPassing, buildUpPlayPassingClass,
buildUpPlayPositioningClass, chanceCreationPassing, chanceCreationPassingClass, chanceCreationCrossing, chanceCreationCrossingClass, chanceCreationShooting,
chanceCreationShootingClass, chanceCreationPositioningClass, defencePressure, defencePressureClass, defenceAggression, defenceAggressionClass,
defenceTeamWidth, defenceTeamWidthClass, defenceDefenderLineClass
from teams_all
group by team_api_id
having max(date)