select * from leagues l 

create table match_all as
select * from match_details md 
join leagues l 
on md.country_id  = l.id

create table match_team_u as
select distinct
season, name, league, stage, home.date, home_team, team_long_name as away_team, home_team_goal, away_team_goal,
home_player_1,
home_player_2,
home_player_3,
home_player_4,
home_player_5,
home_player_6,
home_player_7,
home_player_8,
home_player_9,
home_player_10,
home_player_11,
away_player_1,
away_player_2,
away_player_3,
away_player_4,
away_player_5,
away_player_6,
away_player_7,
away_player_8,
away_player_9,
away_player_10,
away_player_11
from
(select season,name, league, stage, match_all.date, home_team_api_id, team_long_name as home_team, away_team_api_id, home_team_goal, away_team_goal,
home_player_1,
home_player_2,
home_player_3,
home_player_4,
home_player_5,
home_player_6,
home_player_7,
home_player_8,
home_player_9,
home_player_10,
home_player_11,
away_player_1,
away_player_2,
away_player_3,
away_player_4,
away_player_5,
away_player_6,
away_player_7,
away_player_8,
away_player_9,
away_player_10,
away_player_11
from match_all 
join teams_all
on match_all.home_team_api_id = teams_all.team_api_id)home
join teams_all 
on home.away_team_api_id = teams_all.team_api_id




create table home_players as
select 
season,name, league, stage, h10.date, home_team, away_team, home_team_goal, away_team_goal,
player_1,
age_player_1,
height_player_1,
weight_player_1,
player_2,
age_player_2,
height_player_2,
weight_player_2,
home_player_3,
age_player_3,
height_player_3,
weight_player_3,
home_player_4,
age_player_4,
height_player_4,
weight_player_4,
home_player_5,
age_player_4,
height_player_5,
weight_player_5,
home_player_6,
age_player_6,
height_player_6,
weight_player_6,
home_player_7,
age_player_7,
height_player_7,
weight_player_7,
home_player_8,
age_player_8,
height_player_8,
weight_player_8,
home_player_9,
age_player_9,
height_player_9,
weight_player_9,
home_player_10,
age_player_10,
height_player_10,
weight_player_10,
player_name  as home_player_11,
h10.date - birthday as age_player_11,
height as height_player_11,
weight as weight_player_11
from
(select 
season, name, league,stage, h9.date, home_team, away_team, home_team_goal, away_team_goal,
player_1,
age_player_1,
height_player_1,
weight_player_1,
player_2,
age_player_2,
height_player_2,
weight_player_2,
home_player_3,
age_player_3,
height_player_3,
weight_player_3,
home_player_4,
age_player_4,
height_player_4,
weight_player_4,
home_player_5,
age_player_4,
height_player_5,
weight_player_5,
home_player_6,
age_player_6,
height_player_6,
weight_player_6,
home_player_7,
age_player_7,
height_player_7,
weight_player_7,
home_player_8,
age_player_8,
height_player_8,
weight_player_8,
home_player_9,
age_player_9,
height_player_9,
weight_player_9,
player_name  as home_player_10,
h9.date - birthday as age_player_10,
height as height_player_10,
weight as weight_player_10,
home_player_11
from
(select 
season, name, league,stage, h8.date, home_team, away_team, home_team_goal, away_team_goal,
player_1,
age_player_1,
height_player_1,
weight_player_1,
player_2,
age_player_2,
height_player_2,
weight_player_2,
home_player_3,
age_player_3,
height_player_3,
weight_player_3,
home_player_4,
age_player_4,
height_player_4,
weight_player_4,
home_player_5,
age_player_4,
height_player_5,
weight_player_5,
home_player_6,
age_player_6,
height_player_6,
weight_player_6,
home_player_7,
age_player_7,
height_player_7,
weight_player_7,
home_player_8,
age_player_8,
height_player_8,
weight_player_8,
player_name  as home_player_9,
h8.date - birthday as age_player_9,
height as height_player_9,
weight as weight_player_9,
home_player_10,
home_player_11
from
(select 
season,name, league, stage, h7.date, home_team, away_team, home_team_goal, away_team_goal,
player_1,
age_player_1,
height_player_1,
weight_player_1,
player_2,
age_player_2,
height_player_2,
weight_player_2,
home_player_3,
age_player_3,
height_player_3,
weight_player_3,
home_player_4,
age_player_4,
height_player_4,
weight_player_4,
home_player_5,
age_player_4,
height_player_5,
weight_player_5,
home_player_6,
age_player_6,
height_player_6,
weight_player_6,
home_player_7,
age_player_7,
height_player_7,
weight_player_7,
player_name  as home_player_8,
h7.date - birthday as age_player_8,
height as height_player_8,
weight as weight_player_8,
home_player_9,
home_player_10,
home_player_11
from
(select 
season, name, league,stage, h6.date, home_team, away_team, home_team_goal, away_team_goal,
player_1,
age_player_1,
height_player_1,
weight_player_1,
player_2,
age_player_2,
height_player_2,
weight_player_2,
home_player_3,
age_player_3,
height_player_3,
weight_player_3,
home_player_4,
age_player_4,
height_player_4,
weight_player_4,
home_player_5,
age_player_4,
height_player_5,
weight_player_5,
home_player_6,
age_player_6,
height_player_6,
weight_player_6,
player_name  as home_player_7,
h6.date - birthday as age_player_7,
height as height_player_7,
weight as weight_player_7,
home_player_8,
home_player_9,
home_player_10,
home_player_11
from
(select 
season, name, league,stage, h5.date, home_team, away_team, home_team_goal, away_team_goal,
player_1,
age_player_1,
height_player_1,
weight_player_1,
player_2,
age_player_2,
height_player_2,
weight_player_2,
home_player_3,
age_player_3,
height_player_3,
weight_player_3,
home_player_4,
age_player_4,
height_player_4,
weight_player_4,
home_player_5,
age_player_4,
height_player_5,
weight_player_5,
player_name  as home_player_6,
h5.date - birthday as age_player_6,
height as height_player_6,
weight as weight_player_6,
home_player_7,
home_player_8,
home_player_9,
home_player_10,
home_player_11
from
(select 
season, name, league,stage, h4.date, home_team, away_team, home_team_goal, away_team_goal,
player_1,
age_player_1,
height_player_1,
weight_player_1,
player_2,
age_player_2,
height_player_2,
weight_player_2,
home_player_3,
age_player_3,
height_player_3,
weight_player_3,
home_player_4,
age_player_4,
height_player_4,
weight_player_4,
player_name  as home_player_5,
h4.date - birthday as age_player_5,
height as height_player_5,
weight as weight_player_5,
home_player_6,
home_player_7,
home_player_8,
home_player_9,
home_player_10,
home_player_11
from
(select 
season,name, league, stage, h3.date, home_team, away_team, home_team_goal, away_team_goal,
player_1,
age_player_1,
height_player_1,
weight_player_1,
player_2,
age_player_2,
height_player_2,
weight_player_2,
home_player_3,
age_player_3,
height_player_3,
weight_player_3,
player_name  as home_player_4,
h3.date - birthday as age_player_4,
height as height_player_4,
weight as weight_player_4,
home_player_5,
home_player_6,
home_player_7,
home_player_8,
home_player_9,
home_player_10,
home_player_11
from
(select 
season, name, league,stage, h2.date, home_team, away_team, home_team_goal, away_team_goal,
player_1,
age_player_1,
height_player_1,
weight_player_1,
player_2,
age_player_2,
height_player_2,
weight_player_2,
player_name  as home_player_3,
h2.date - birthday as age_player_3,
height as height_player_3,
weight as weight_player_3,
home_player_4,
home_player_5,
home_player_6,
home_player_7,
home_player_8,
home_player_9,
home_player_10,
home_player_11
from
(select 
season,name, league, stage, h1.date, home_team, away_team, home_team_goal, away_team_goal,
player_1,
age_player_1,
height_player_1,
weight_player_1,
player_name as player_2,
h1.date - birthday as age_player_2,
height as height_player_2,
weight as weight_player_2,
home_player_3,
home_player_4,
home_player_5,
home_player_6,
home_player_7,
home_player_8,
home_player_9,
home_player_10,
home_player_11
from
(select 
season,name, league, stage, match_team_u.date, home_team, away_team, home_team_goal, away_team_goal,
player_name as player_1,
match_team_u.date - birthday as age_player_1,
height as height_player_1,
weight as weight_player_1,
home_player_2,
home_player_3,
home_player_4,
home_player_5,
home_player_6,
home_player_7,
home_player_8,
home_player_9,
home_player_10,
home_player_11
from match_team_u
join players_all on
match_team_u.home_player_1 = players_all.player_api_id)h1
join players_all on
h1.home_player_2 = players_all.player_api_id)h2
join players_all on
h2.home_player_3 = players_all.player_api_id)h3
join players_all on
h3.home_player_4 = players_all.player_api_id)h4
join players_all on
h4.home_player_5 = players_all.player_api_id)h5
join players_all on
h5.home_player_6 = players_all.player_api_id)h6
join players_all on
h6.home_player_7 = players_all.player_api_id)h7
join players_all on
h7.home_player_8 = players_all.player_api_id)h8
join players_all on
h8.home_player_9 = players_all.player_api_id)h9
join players_all on
h9.home_player_10 = players_all.player_api_id)h10
join players_all on
h10.home_player_11 = players_all.player_api_id








create table away_players as
select 
season,name, league, stage, a10.date, home_team, away_team, home_team_goal, away_team_goal,
player_1,
age_player_1,
height_player_1,
weight_player_1,
player_2,
age_player_2,
height_player_2,
weight_player_2,
player_3,
age_player_3,
height_player_3,
weight_player_3,
player_4,
age_player_4,
height_player_4,
weight_player_4,
player_5,
age_player_5,
height_player_5,
weight_player_5,
player_6,
age_player_6,
height_player_6,
weight_player_6,
player_7,
age_player_7,
height_player_7,
weight_player_7,
player_8,
age_player_8,
height_player_8,
weight_player_8,
player_9,
age_player_9,
height_player_9,
weight_player_9,
player_10,
age_player_10,
height_player_10,
weight_player_10,
player_name as player_11,
a10.date - birthday as age_player_11,
height as height_player_11,
weight as weight_player_11
from
(select 
season,name, league, stage, a9.date, home_team, away_team, home_team_goal, away_team_goal,
player_1,
age_player_1,
height_player_1,
weight_player_1,
player_2,
age_player_2,
height_player_2,
weight_player_2,
player_3,
age_player_3,
height_player_3,
weight_player_3,
player_4,
age_player_4,
height_player_4,
weight_player_4,
player_5,
age_player_5,
height_player_5,
weight_player_5,
player_6,
age_player_6,
height_player_6,
weight_player_6,
player_7,
age_player_7,
height_player_7,
weight_player_7,
player_8,
age_player_8,
height_player_8,
weight_player_8,
player_9,
age_player_9,
height_player_9,
weight_player_9,
player_name as player_10,
a9.date - birthday as age_player_10,
height as height_player_10,
weight as weight_player_10,
away_player_11
from
(select 
season,name, league, stage, a8.date, home_team, away_team, home_team_goal, away_team_goal,
player_1,
age_player_1,
height_player_1,
weight_player_1,
player_2,
age_player_2,
height_player_2,
weight_player_2,
player_3,
age_player_3,
height_player_3,
weight_player_3,
player_4,
age_player_4,
height_player_4,
weight_player_4,
player_5,
age_player_5,
height_player_5,
weight_player_5,
player_6,
age_player_6,
height_player_6,
weight_player_6,
player_7,
age_player_7,
height_player_7,
weight_player_7,
player_8,
age_player_8,
height_player_8,
weight_player_8,
player_name as player_9,
a8.date - birthday as age_player_9,
height as height_player_9,
weight as weight_player_9,
away_player_10,
away_player_11
from
(select 
season,name, league, stage, a7.date, home_team, away_team, home_team_goal, away_team_goal,
player_1,
age_player_1,
height_player_1,
weight_player_1,
player_2,
age_player_2,
height_player_2,
weight_player_2,
player_3,
age_player_3,
height_player_3,
weight_player_3,
player_4,
age_player_4,
height_player_4,
weight_player_4,
player_5,
age_player_5,
height_player_5,
weight_player_5,
player_6,
age_player_6,
height_player_6,
weight_player_6,
player_7,
age_player_7,
height_player_7,
weight_player_7,
player_name as player_8,
a7.date - birthday as age_player_8,
height as height_player_8,
weight as weight_player_8,
away_player_9,
away_player_10,
away_player_11
from
(select 
season,name, league, stage, a6.date, home_team, away_team, home_team_goal, away_team_goal,
player_1,
age_player_1,
height_player_1,
weight_player_1,
player_2,
age_player_2,
height_player_2,
weight_player_2,
player_3,
age_player_3,
height_player_3,
weight_player_3,
player_4,
age_player_4,
height_player_4,
weight_player_4,
player_5,
age_player_5,
height_player_5,
weight_player_5,
player_6,
age_player_6,
height_player_6,
weight_player_6,
player_name as player_7,
a6.date - birthday as age_player_7,
height as height_player_7,
weight as weight_player_7,
away_player_8,
away_player_9,
away_player_10,
away_player_11
from
(select 
season,name, league, stage, a5.date, home_team, away_team, home_team_goal, away_team_goal,
player_1,
age_player_1,
height_player_1,
weight_player_1,
player_2,
age_player_2,
height_player_2,
weight_player_2,
player_3,
age_player_3,
height_player_3,
weight_player_3,
player_4,
age_player_4,
height_player_4,
weight_player_4,
player_5,
age_player_5,
height_player_5,
weight_player_5,
player_name as player_6,
a5.date - birthday as age_player_6,
height as height_player_6,
weight as weight_player_6,
away_player_7,
away_player_8,
away_player_9,
away_player_10,
away_player_11
from
(select 
season,name, league, stage, a4.date, home_team, away_team, home_team_goal, away_team_goal,
player_1,
age_player_1,
height_player_1,
weight_player_1,
player_2,
age_player_2,
height_player_2,
weight_player_2,
player_3,
age_player_3,
height_player_3,
weight_player_3,
player_4,
age_player_4,
height_player_4,
weight_player_4,
player_name as player_5,
a4.date - birthday as age_player_5,
height as height_player_5,
weight as weight_player_5,
away_player_6,
away_player_7,
away_player_8,
away_player_9,
away_player_10,
away_player_11
from
(select 
season,name, league, stage, a3.date, home_team, away_team, home_team_goal, away_team_goal,
player_1,
age_player_1,
height_player_1,
weight_player_1,
player_2,
age_player_2,
height_player_2,
weight_player_2,
player_3,
age_player_3,
height_player_3,
weight_player_3,
player_name as player_4,
a3.date - birthday as age_player_4,
height as height_player_4,
weight as weight_player_4,
away_player_5,
away_player_6,
away_player_7,
away_player_8,
away_player_9,
away_player_10,
away_player_11
from
(select 
season,name, league, stage, a2.date, home_team, away_team, home_team_goal, away_team_goal,
player_1,
age_player_1,
height_player_1,
weight_player_1,
player_2,
age_player_2,
height_player_2,
weight_player_2,
player_name as player_3,
a2.date - birthday as age_player_3,
height as height_player_3,
weight as weight_player_3,
away_player_4,
away_player_5,
away_player_6,
away_player_7,
away_player_8,
away_player_9,
away_player_10,
away_player_11
from
(select 
season,name, league, stage, a1.date, home_team, away_team, home_team_goal, away_team_goal,
player_1,
age_player_1,
height_player_1,
weight_player_1,
player_name as player_2,
a1.date - birthday as age_player_2,
height as height_player_2,
weight as weight_player_2,
away_player_3,
away_player_4,
away_player_5,
away_player_6,
away_player_7,
away_player_8,
away_player_9,
away_player_10,
away_player_11
from
(select 
season,name, league, stage, match_team_u.date, home_team, away_team, home_team_goal, away_team_goal,
player_name as player_1,
match_team_u.date - birthday as age_player_1,
height as height_player_1,
weight as weight_player_1,
away_player_2,
away_player_3,
away_player_4,
away_player_5,
away_player_6,
away_player_7,
away_player_8,
away_player_9,
away_player_10,
away_player_11
from match_team_u
join players_all on
match_team_u.away_player_1 = players_all.player_api_id)a1
join players_all on
a1.away_player_2 = players_all.player_api_id)a2
join players_all on
a2.away_player_3 = players_all.player_api_id)a3
join players_all on
a3.away_player_4 = players_all.player_api_id)a4
join players_all on
a4.away_player_5 = players_all.player_api_id)a5
join players_all on
a5.away_player_6 = players_all.player_api_id)a6
join players_all on
a6.away_player_7 = players_all.player_api_id)a7
join players_all on
a7.away_player_8 = players_all.player_api_id)a8
join players_all on
a8.away_player_9 = players_all.player_api_id)a9
join players_all on
a9.away_player_10 = players_all.player_api_id)a10
join players_all on
a10.away_player_11 = players_all.player_api_id


create table players_all as
select * from players p 
join players_details pd 
on p.player_api_id = pd.player_api_id 

select * from players_details pd 

create table teams_all as
select * from teams t
join teams_details td 
on t.team_api_id = td.team_api_id 

select * from teams_details td 

create table buck as
select season, name, league, stage,teams_all.team_long_name, home_team_goal, away_team_goal, 
b365h, b365d, b365a, bwh, bwd, bwa, iwh, iwd, iwa, lbh, lbd, lba, psh, psd, psa, whh, whd, wha, sjh, sjd, sja, vch, vcd, vca, gbh, gbd, gba,
bsh, bsd, bsa
from match_all
join teams_all 
on match_all.home_team_api_id = team_api_id